// Generated by https://quicktype.io

export interface LoginRes {
  message: string;
  ok: boolean;
  token: string;
}

// Generated by https://quicktype.io

export interface LoginCall {
  username: string;
  password: string;
}

export interface Rol {
  id: number;
  name: string;
  description: string;
  status: boolean;
  operationTypes: [
    {
      id: number;
      text: string;
    }
  ];
}
