// Generated by https://quicktype.io

export interface RequestResetPasswoodRes {
  message: string;
  ok:      boolean;
  token:   string;
}

// Generated by https://quicktype.io

export interface RequestResetPasswordCall {
  password: string;
  
}
