// Generated by https://quicktype.io

export interface ResetPasswoodRes {
  message: string;
  ok:      boolean;
  token:   string;
}

// Generated by https://quicktype.io

export interface ResetPasswordCall {
  email: string;
}
