export const paisesListado: Array<any> = [
  {
    name: 'Cuba',
    states: [
      { name: 'Pinar del Río' },
      { name: 'Artemisa' },
      { name: 'La Habana' },
      { name: 'Mayabeque' },
      { name: 'Matanzas' },
      { name: 'Cienfuegos' },
      { name: 'Villa Clara' },
      { name: 'Sancti Spíritus' },
      { name: 'Ciego de Ávila' },
      { name: 'Camagüey' },
      { name: 'Las Tunas' },
      { name: 'Granma' },
      { name: 'Holguín' },
      { name: 'Santiago de Cuba' },
      { name: 'Guantánamo' },
      { name: 'Isla de la Juventud' },
    ],
  }/*,
  {
    name: 'Brasil',
    states: [
      {
        name: 'São Paulo',
      },
      {
        name: 'Río de Janeiro',
      },
      {
        name: 'Distrito Federal',
      },
      {
        name: 'Bahía',
      },
      {
        name: 'Ceará',
      },
      {
        name: 'Minas Gerais',
      },
      {
        name: 'Amazonas',
      },
      {
        name: 'Paraná',
      },
      {
        name: 'Pernambuco',
      },
      {
        name: 'Goiás',
      },
      {
        name: 'Pará',
      },
      {
        name: 'Río Grande del Sur',
      },
      {
        name: 'Mato Grosso del Sur',
      },
      {
        name: 'Alagoas',
      },
      {
        name: 'Río Grande del Norte',
      },
    ],
  },
  {
    name: 'Mexico',
    states: [
      { name: 'Aguascalientes' },
      { name: 'Baja California' },
      { name: 'Baja California Sur' },
      { name: 'Campeche' },
      { name: 'Chiapas' },
      { name: 'Chihuahua' },
      { name: 'Ciudad de México' },
      { name: 'Coahuila' },
      { name: 'Colima' },
      { name: 'Durango' },
      { name: 'Guanajuato' },
      { name: 'Guerrero' },
      { name: 'Hidalgo' },
      { name: 'Jalisco' },
      { name: 'México' },
      { name: 'Michoacán' },
      { name: 'Morelos' },
      { name: 'Nayarit' },
      { name: 'Nuevo León' },
      { name: 'Oaxaca' },
      { name: 'Puebla' },
      { name: 'Querétaro' },
      { name: 'Quintana Roo' },
      { name: 'San Luis Potosí' },
      { name: 'Sinaloa' },
      { name: 'Sonora' },
      { name: 'Tabasco' },
      { name: 'Tamaulipas' },
      { name: 'Tlaxcala' },
      { name: 'Veracruz' },
      { name: 'Yucatán' },
      { name: 'Zacatecas' },
    ],
  },
  {
    name: 'Estados Unidos',
    states: [
      { name: 'Nueva York' },
      { name: 'Los Ángeles' },
      { name: 'Chicago' },
      { name: 'Houston' },
      { name: 'Phoenix' },
      { name: 'Filadelfia' },
      { name: 'San Antonio' },
      { name: 'San Diego' },
      { name: 'Dallas' },
      { name: 'San José' },
      { name: 'Detroit' },
      { name: 'Jacksonville' },
      { name: 'San Francisco' },
      { name: 'Indianápolis' },
      { name: 'Austin' },
      { name: 'Columbus' },
      { name: 'Fort Worth' },
      { name: 'Charlotte' },
      { name: 'Memphis' },
      { name: 'Baltimore' },
    ],
  },
  {
    name: 'Canadá',
    states: [
      { name: 'Toronto' },
      { name: 'Montreal' },
      { name: 'Vancouver' },
      { name: 'Calgary' },
      { name: 'Edmonton' },
      { name: 'Ottawa' },
      { name: 'Ciudad de Quebec' },
      { name: 'Hamilton' },
      { name: 'Winnipeg' },
      { name: 'Kitchener' },
      { name: 'London' },
      { name: 'Victoria' },
      { name: 'Saint Catharines-Niagara' },
      { name: 'Oshawa' },
      { name: 'Windsor' },
      { name: 'Halifax' },
      { name: 'Saskatoon' },
      { name: 'Barrie' },
      { name: 'Regina' },
      { name: 'San Juan de Terranova' },
    ],
  },
  {
    name: 'Ecuador',
    states: [
      { name: 'Guayaquil' },
      { name: 'Quito' },
      { name: 'Cuenca' },
      { name: 'Santo Domingo' },
      { name: 'Machala' },
      { name: 'Durán' },
      { name: 'Manta' },
      { name: 'Portoviejo' },
      { name: 'Loja' },
      { name: 'Ambato' },
      { name: 'Guayas' },
      { name: 'Pichincha' },
      { name: 'Azuay' },
      { name: 'Santo Domingo de los Tsáchilas' },
      { name: 'El Oro' },
      { name: 'Guayas' },
      { name: 'Manabí' },
      { name: 'Tungurahua' },
    ],
  },
  {
    name: 'Colombia',
    states: [
      { name: 'Leticia' },
      { name: 'Medellín' },
      { name: 'Arauca' },
      { name: 'Barranquilla' },
      { name: 'Cartagena' },
      { name: 'Tunja' },
      { name: 'Manizales' },
      { name: 'Florencia' },
      { name: 'Yopal' },
      { name: 'Popayán' },
      { name: 'Valledupar' },
      { name: 'Quibdó' },
      { name: 'Montería' },
      { name: 'Bogotá' },
      { name: 'Inírida' },
      { name: 'San José del Guaviare' },
      { name: 'Neiva' },
      { name: 'Riohacha' },
      { name: 'Santa Marta' },
      { name: 'Villavicencio' },
      { name: 'Pasto' },
      { name: 'Cúcuta' },
      { name: 'Mocoa' },
      { name: 'Armenia' },
      { name: 'Pereira' },
      { name: 'San Andrés' },
      { name: 'Bucaramanga' },
      { name: 'Sincelejo' },
      { name: 'Ibagué' },
      { name: 'Cali' },
      { name: 'Mitú' },
      { name: 'Puerto Carreño' },
      { name: 'Bogotá' },
    ],
  },
  {
    name: 'Venezuela',
    states: [
      { name: 'Distrito Capital' },
      { name: 'Zulia' },
      { name: 'Lara' },
      { name: 'Carabobo' },
      { name: 'Bolívar' },
      { name: 'Monagas' },
      { name: 'Anzoátegui' },
      { name: 'Aragua' },
      { name: 'Sucre' },
      { name: 'Barinas' },
      { name: 'Táchira' },
      { name: 'Falcón' },
      { name: 'Miranda' },
      { name: 'Mérida' },
    ],
  },
  {
    name: 'Bolivia',
    states: [
      { name: 'Santa Cruz de la Sierra' },
      { name: 'El Alto' },
      { name: 'La Paz' },
      { name: 'Oruro' },
      { name: 'Cochabamba' },
      { name: 'Sucre' },
      { name: 'Potosí' },
      { name: 'Tarija' },
      { name: 'Sacaba' },
      { name: 'Quillacollo' },
    ],
  },
  {
    name: 'Uruguay',
    states: [
      { name: 'Montevideo' },
      { name: 'Ciudad de la Costa' },
      { name: 'Salto' },
      { name: 'Paysandú' },
      { name: 'Maldonado' },
      { name: 'Rivera' },
      { name: 'Las Piedras' },
      { name: 'Tacuarembó' },
      { name: 'Melo' },
      { name: 'Artigas' },
      { name: 'Mercedes' },
      { name: 'Minas' },
      { name: 'San José de Mayo' },
      { name: 'Durazno' },
      { name: 'Florida' },
      { name: 'Treinta y Tres' },
      { name: 'Barros Blancos' },
      { name: 'Ciudad del Plata' },
      { name: 'San Carlos' },
      { name: 'Colonia del Sacramento' },
      { name: 'Pando' },
      { name: 'Rocha' },
      { name: 'Fray Bentos' },
      { name: 'Trinidad' },
      { name: 'La Paz' },
      { name: 'Canelones' },
      { name: 'Dolores' },
      { name: 'Carmelo' },
      { name: 'Bella Unión' },
      { name: 'Young' },
      { name: 'Santa Lucía' },
      { name: 'Progreso' },
      { name: 'Río Branco' },
      { name: 'Paso de los Toros' },
      { name: 'Juan Lacaze' },
      { name: 'Punta del Este' },
      { name: 'Nueva Helvecia' },
      { name: 'Libertad' },
      { name: 'Rosario' },
      { name: 'Nueva Palmira' },
    ],
  }*/
];
